### ISSUE TITLE
Add donors and partner logos

### ISSUE THREAD

**Issue by thomas-maschler** [crowdcover/logging-roads#8] opened 2015-05-06 01:15 UTC
Add donors logos (USAID, DIFD and NORAD) -> will have to confirm again with Matt if this is the correct list.
Parters are Moabi, WRI, HOT, OSM. who else?

**Comment by jameslaneconkling** [comment] 2015-05-11 16:25
@thomas-maschler if you have any of these logos, can you add to **GDrive > assets**?

Also, should this be a new page, or included in the About page.  (I suggest the latter, unless there's enough content on partners/donors to justify an entire page)

**Comment by thomas-maschler** [comment] 2015-05-11 17:00
USAID
https://drive.google.com/open?id=0B58e-2phIRx1NjlSN3dWaGRDQTg&authuser=0

UK
https://drive.google.com/open?id=0B58e-2phIRx1NjlSN3dWaGRDQTg&authuser=0

Norway
https://drive.google.com/open?id=0B58e-2phIRx1QWQzT21XclZsMVE&authuser=0

UMD
https://drive.google.com/open?id=0B-Ojr3OO5BkDSlNQTC05aXUtOHM&authuser=0

WRI
http://brand.wri.org/brand-assets/logos

**Comment by thomas-maschler** [comment] 2015-05-14 13:13
We could list the partners at the bottom of the front page, next to the twitter feeds.
There is plenty of space.
Have a look at our GFW page (front page, bottom) I think they did a nice job.

**Comment by jameslaneconkling** [comment] 2015-05-14 13:17
agreed.

**Comment by jameslaneconkling** [comment] 2015-05-25 17:07
@thomas-maschler the link to the UK logo is a duplicate of the USAID logo.  Can you update?

**Comment by thomas-maschler** [comment] 2015-05-25 17:14
https://drive.google.com/open?id=0B58e-2phIRx1MTB0Mk04enN6QkE&authuser=0

**Comment by jameslaneconkling** [comment] 2015-05-25 18:34
OK, added logos except for UMD b/c I couldn't figure out how to convert its white background to transparent.  @BKessle you have any experience with that?

**Comment by thomas-maschler** [comment] 2015-05-25 22:04
![umd](https://cloud.githubusercontent.com/assets/7538337/7802655/872fb254-0308-11e5-8349-ecb30c5e21b0.png)

**Comment by thomas-maschler** [comment] 2015-05-25 22:33
Will check if we have a Adobe Illustrator license somewhere to edit the original vector file to avoid the ugly white borders around the letters

**Comment by jameslaneconkling** [comment] 2015-05-27 10:19
OK.  Ditto, USAID logo would also look cleaner if we could modify the original svg.

Closing for now.  Reopen if we have access to svgs for UMD/USAID.

**Closed as completed by jameslaneconkling** 2015-05-27 10:19 UTC
